# Stock Sentiment Analysis using News Headlines

In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("Data.csv", encoding= "ISO-8859-1")

In [3]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

Label is our dependent feature here

In [5]:
df.shape

(4101, 27)

In [6]:
df.describe

<bound method NDFrame.describe of             Date  Label                                               Top1  \
0     2000-01-03      0  A 'hindrance to operations': extracts from the...   
1     2000-01-04      0                                          Scorecard   
2     2000-01-05      0                  Coventry caught on counter by Flo   
3     2000-01-06      1                      Pilgrim knows how to progress   
4     2000-01-07      1                               Hitches and Horlocks   
...          ...    ...                                                ...   
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                             

#### Creating train and test dataset

Always split dataset datewise in time series analysis, as when new data comes up, it would be performing based on previous data

In [23]:
train= df[df['Date']<'2010101']
test= df[df['Date']>'20141231']

## Data Preprocessing
#### Removing puncutations marks and special characters

In [9]:
data= train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ", regex=True, inplace=True)

##replacing all other charcters than alpphabets with blank space

#### Removing columns names for ease of access

In [10]:
list1= [i for i in range(25)]
new_index=[str(i) for i in list1]
data.columns= new_index

data.head(3)

0  \
0  A  hindrance to operations   extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   

                                    1  \
0                           Scorecard   
1                 The best lake scene   
2  United s rivals on the road to Rio   

                                               2  \
0                Hughes  instant hit buoys Blues   
1                  Leader  German sleaze inquiry   
2  Thatcher issues defence before trial by video   

                                               3  \
0       Jack gets his skates on at ice cold Alex   
1                                  Cheerio  boyo   
2  Police help Smith lay down the law at Everton   

                                             4  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees    
2                                England on the rack   

                                                 6  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees    
2  Pakistan retaliate with call for video of Walsh   

                                      7  \
0     Gunners so wide of an easy target   
1                Has Cubie killed fees    
2  Cullinan continues his Cape monopoly   

                                                   8  \
0      Derby raise a glass to Strupar s debut double   
1  Hopkins  furious  at Foster s lack of Hannibal...   
2             McGrath puts India out of their misery   

                                          9  ...  \
0  Southgate strikes  Leeds pay the penalty  ...   
1                    Has Cubie killed fees   ...   
2            Blair Witch bandwagon rolls on  ...   

                                         15  \
0  Flintoff injury piles on woe for England   
1                      On the critical list   
2               South Melbourne  Australia    

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa  Mexico    

                                    17  \
0  Kohl s successor drawn into scandal   
1                          Dear doctor   
2                  Real Madrid  Spain    

                                                  18  \
0               The difference between men and women   
1  Irish court halts IRA man s extradition to Nor...   
2                          Raja Casablanca  Morocco    

                                                  19  \
0                Sara Denver  nurse turned solicitor   
1  Burundi peace initiative fades after rebels re...   
2                               Corinthians  Brazil    

                                               20  \
0  Diana s landmine crusade put Tories in a panic   
1            PE points the way forward to the ECB   
2                              Tony s pet project   

                                                  21                 22  \
0  Yeltsin s resignation caught opposition flat f...   Russian roulette   
1  Campaigners keep up pressure on Nazi war crime...     Jane Ratcliffe   
2                            Al Nassr  Saudi Arabia   Ideal Holmes show   

                                                  23  \
0                                           Sold out   
1  Yet more things you wouldn t know without the ...   
2               Pinochet leaves hospital after tests   

                             24  
0            Recovering a title  
1  Millennium bug fails to bite  
2                  Useful links  

[3 rows x 25 columns]

#### coverting all headlines to lowercase 

In [12]:
for index in new_index:
    data[index]= data[index].str.lower()

data.head(1)

0          1  \
0  a  hindrance to operations   extracts from the...  scorecard   

                                 2                                         3  \
0  hughes  instant hit buoys blues  jack gets his skates on at ice cold alex   

                                        4  \
0  chaos as maracana builds up for united   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   

                                               8  \
0  derby raise a glass to strupar s debut double   

                                          9  ...  \
0  southgate strikes  leeds pay the penalty  ...   

                                         15  \
0  flintoff injury piles on woe for england   

                                                  16  \
0  hunters threaten jospin with new battle of the...   

                                    17                                    18  \
0  kohl s successor drawn into scandal  the difference between men and women   

                                    19  \
0  sara denver  nurse turned solicitor   

                                               20  \
0  diana s landmine crusade put tories in a panic   

                                                  21                22  \
0  yeltsin s resignation caught opposition flat f...  russian roulette   

         23                  24  
0  sold out  recovering a title  

[1 rows x 25 columns]

#### combining all headlines
#### converting them in vector then

In [14]:
' '.join(str(x) for x in data.iloc[1,0:25]) 
#with space in between joining them

'scorecard the best lake scene leader  german sleaze inquiry cheerio  boyo the main recommendations has cubie killed fees  has cubie killed fees  has cubie killed fees  hopkins  furious  at foster s lack of hannibal appetite has cubie killed fees  a tale of two tails i say what i like and i like what i say elbows  eyes and nipples task force to assess risk of asteroid collision how i found myself at last on the critical list the timing of their lives dear doctor irish court halts ira man s extradition to northern ireland burundi peace initiative fades after rebels reject mandela as mediator pe points the way forward to the ecb campaigners keep up pressure on nazi war crimes suspect jane ratcliffe yet more things you wouldn t know without the movies millennium bug fails to bite'

combining all records

In [15]:
headlines=[]

for row in range(0, len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]) )

In [16]:
headlines[0]

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

#### countvectorizer 
helps in creating bag of words


In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

#### implementing Bag of Words


In [19]:
countvector= CountVectorizer(ngram_range=(2,2))
traindataset= countvector.fit_transform(headlines)

#### implementing random forest

In [20]:
randomclassifier= RandomForestClassifier(n_estimators=200, criterion='entropy')
randomclassifier.fit(traindataset, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

#### Predict for test dataset

In [26]:
test_transform=[]
for row in range(0, len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset= countvector.transform(test_transform)
predictions= randomclassifier.predict(test_dataset)

test_dataset[0]

sparse matrix meaning containing only 0 and 1

In [29]:
predictions

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

#### Checking Accuracy

In [30]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [32]:
matrix= confusion_matrix(test['Label'], predictions)
print(matrix)

score= accuracy_score(test['Label'], predictions)
print(score)

report = classification_report(test['Label'], predictions)
print(report)

[[ 22 164]
 [ 16 176]]
0.5238095238095238
              precision    recall  f1-score   support

           0       0.58      0.12      0.20       186
           1       0.52      0.92      0.66       192

    accuracy                           0.52       378
   macro avg       0.55      0.52      0.43       378
weighted avg       0.55      0.52      0.43       378



1. this is showing dataset is not imbalanced
2. decent accuracy
3. 

using TFIDF now to check if accuracy increase or not

#### TF-IDF

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [37]:
tfidfvector= TfidfVectorizer(ngram_range=(2,2))
traindataset= tfidfvector.fit_transform(headlines)

In [38]:
randomclassifier= RandomForestClassifier(n_estimators=200, criterion='entropy')
randomclassifier.fit(traindataset, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [39]:
test_transform=[]
for row in range(0, len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset= tfidfvector.transform(test_transform)
predictions= randomclassifier.predict(test_dataset)

In [40]:
matrix= confusion_matrix(test['Label'], predictions)
print(matrix)

score= accuracy_score(test['Label'], predictions)
print(score)

report = classification_report(test['Label'], predictions)
print(report)

[[ 62 124]
 [ 45 147]]
0.5529100529100529
              precision    recall  f1-score   support

           0       0.58      0.33      0.42       186
           1       0.54      0.77      0.63       192

    accuracy                           0.55       378
   macro avg       0.56      0.55      0.53       378
weighted avg       0.56      0.55      0.53       378



### ACcuracy increased lilltle bit

Now using naive bayes instead of random forest

#### Naive Bayes

In [45]:
from sklearn.naive_bayes import MultinomialNB

In [46]:
naive= MultinomialNB()
naive.fit(traindataset, train['Label'])

MultinomialNB()

In [47]:
test_transform=[]
for row in range(0, len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))

test_dataset= countvector.transform(test_transform)
predictions= naive.predict(test_dataset)

In [48]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [49]:
matrix= confusion_matrix(test['Label'], predictions)
print(matrix)

score= accuracy_score(test['Label'], predictions)
print(score)

report = classification_report(test['Label'], predictions)
print(report)

[[  0 186]
 [  0 192]]
0.5079365079365079
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       186
           1       0.51      1.00      0.67       192

    accuracy                           0.51       378
   macro avg       0.25      0.50      0.34       378
weighted avg       0.26      0.51      0.34       378



C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
